package compat

// Tests SQL generated by Go ORM tools (golang-migrate, GORM, Ent, sqlc).
// Verifies that real-world ORM statements produce identical results.

import (
	"database/sql"
	"fmt"
	"strings"
	"testing"
	"time"
)

// normalizeDeclTypeTimes normalizes time.Time values back to text for comparison,
// since driver handles datetime as text while mattn/go-sqlite3 parses it to time.Time.
// ormStep is one generated statement and its arguments.
type ormStep struct {
	q    string
	args []any
}

// runORMScript replays steps through both engines and compares each result. It
// reports the FIRST divergence per script in full and then keeps going, so one
// early difference does not hide the rest.
func runORMScript(t *testing.T, name string, steps []ormStep) {
	t.Helper()
	t.Run(name, func(t *testing.T) {
		c, m := boundPair(t, nil)
		n := 0
		for i, st := range steps {
			cv := normalizeDeclTypeTimes(boundRows(c, st.q, st.args...))
			mv := normalizeDeclTypeTimes(boundRows(m, st.q, st.args...))
			if cv != mv {
				n++
				t.Errorf("step %d: %s with %v\n  cgo:    %s\n  musql: %s", i, st.q, st.args, cv, mv)
			}
		}
		if n > 0 {
			t.Errorf("%d of %d generated statements diverged", n, len(steps))
		}
	})
}

// TestGolangMigrateSQL is golang-migrate's sqlite3 driver: it keeps one row in
// schema_migrations, wraps each migration in a transaction, and reads the version
// back with a LIMIT 1.
func TestGolangMigrateSQL(t *testing.T) {
	runORMScript(t, "golang-migrate", []ormStep{
		{`PRAGMA foreign_keys = ON`, nil},
		{`CREATE TABLE IF NOT EXISTS schema_migrations (version uint64,dirty bool)`, nil},
		{`CREATE UNIQUE INDEX IF NOT EXISTS version_unique ON schema_migrations (version)`, nil},
		{`SELECT version, dirty FROM schema_migrations LIMIT 1`, nil},
		{`DELETE FROM schema_migrations`, nil},
		{`INSERT INTO schema_migrations (version, dirty) VALUES (?, ?)`, []any{1, true}},
		{`SELECT version, dirty FROM schema_migrations LIMIT 1`, nil},
		// The migration body itself, then the version flipped clean.
		{`CREATE TABLE tenants (id INTEGER PRIMARY KEY, slug TEXT NOT NULL UNIQUE, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP)`, nil},
		{`CREATE TABLE accounts (id INTEGER PRIMARY KEY, tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE, email TEXT NOT NULL, CONSTRAINT accounts_email_uniq UNIQUE (tenant_id, email))`, nil},
		{`CREATE INDEX IF NOT EXISTS accounts_tenant_idx ON accounts (tenant_id)`, nil},
		{`DELETE FROM schema_migrations`, nil},
		{`INSERT INTO schema_migrations (version, dirty) VALUES (?, ?)`, []any{1, false}},
		{`SELECT version, dirty FROM schema_migrations LIMIT 1`, nil},
		// A second migration that alters, which is the shape most likely to break.
		{`ALTER TABLE accounts ADD COLUMN status TEXT NOT NULL DEFAULT 'active'`, nil},
		{`ALTER TABLE accounts RENAME COLUMN email TO email_address`, nil},
		{`SELECT sql FROM sqlite_master WHERE type='table' AND name='accounts'`, nil},
		{`DELETE FROM schema_migrations`, nil},
		{`INSERT INTO schema_migrations (version, dirty) VALUES (?, ?)`, []any{2, false}},
		// The DOWN migration, and the FK cascade it relies on.
		{`INSERT INTO tenants (slug) VALUES (?)`, []any{"acme"}},
		{`INSERT INTO accounts (tenant_id, email_address) VALUES (?, ?)`, []any{1, "a@x"}},
		{`SELECT count(*) FROM accounts`, nil},
		{`DELETE FROM tenants WHERE slug = ?`, []any{"acme"}},
		{`SELECT count(*) FROM accounts`, nil},
		{`DROP INDEX IF EXISTS accounts_tenant_idx`, nil},
		{`DROP TABLE IF EXISTS accounts`, nil},
		{`DROP TABLE IF EXISTS tenants`, nil},
		{`SELECT name FROM sqlite_master WHERE type='table' ORDER BY name`, nil},
	})
}

// TestGORMGeneratedSQL is GORM's sqlite driver: backtick-quoted identifiers, the
// sqlite_master and PRAGMA probes its migrator uses, soft deletes, its upsert
// (clause.OnConflict), batch inserts, preloads as IN-lists, and its Count.
func TestGORMGeneratedSQL(t *testing.T) {
	runORMScript(t, "gorm", []ormStep{
		// Migrator: does the table exist, then create it.
		{"SELECT count(*) FROM sqlite_master WHERE type='table' AND name=?", []any{"companies"}},
		{"CREATE TABLE `companies` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text)", nil},
		{"CREATE TABLE `users` (`id` integer PRIMARY KEY AUTOINCREMENT,`created_at` datetime,`updated_at` datetime,`deleted_at` datetime,`name` text,`age` integer DEFAULT 0,`email` text,`company_id` integer,CONSTRAINT `fk_companies_users` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`))", nil},
		{"CREATE UNIQUE INDEX `idx_users_email` ON `users`(`email`)", nil},
		{"CREATE INDEX `idx_users_deleted_at` ON `users`(`deleted_at`)", nil},
		// Migrator: the introspection it does on every AutoMigrate.
		{"SELECT sql FROM sqlite_master WHERE type = 'table' AND tbl_name = ? AND name = ?", []any{"users", "users"}},
		{"PRAGMA table_info(`users`)", nil},
		{"PRAGMA index_list(`users`)", nil},
		{"PRAGMA index_info(`idx_users_email`)", nil},
		{"SELECT count(*) FROM sqlite_master WHERE type='index' AND tbl_name=? AND name=?", []any{"users", "idx_users_email"}},
		// Create, with the RETURNING GORM uses to fill the model back.
		{"INSERT INTO `companies` (`created_at`,`updated_at`,`deleted_at`,`name`) VALUES (?,?,?,?) RETURNING `id`", []any{"2024-01-01 00:00:00", "2024-01-01 00:00:00", nil, "Acme"}},
		{"INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`email`,`company_id`) VALUES (?,?,?,?,?,?,?) RETURNING `id`", []any{"2024-01-01 00:00:00", "2024-01-01 00:00:00", nil, "alice", 30, "a@x", 1}},
		// A BATCH insert: one statement, many VALUES tuples.
		{"INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`email`,`company_id`) VALUES (?,?,?,?,?,?,?),(?,?,?,?,?,?,?),(?,?,?,?,?,?,?) RETURNING `id`", []any{
			"2024-01-02 00:00:00", "2024-01-02 00:00:00", nil, "bob", 40, "b@x", 1,
			"2024-01-03 00:00:00", "2024-01-03 00:00:00", nil, "carol", 50, "c@x", 1,
			"2024-01-04 00:00:00", "2024-01-04 00:00:00", nil, "dave", nil, "d@x", nil}},
		// First / Find / Take, with the soft-delete predicate GORM always adds.
		{"SELECT * FROM `users` WHERE `users`.`deleted_at` IS NULL ORDER BY `users`.`id` LIMIT ?", []any{1}},
		{"SELECT * FROM `users` WHERE `users`.`deleted_at` IS NULL ORDER BY `users`.`id` DESC LIMIT ?", []any{1}},
		{"SELECT * FROM `users` WHERE name = ? AND `users`.`deleted_at` IS NULL", []any{"bob"}},
		{"SELECT * FROM `users` WHERE age > ? AND `users`.`deleted_at` IS NULL ORDER BY age DESC LIMIT ? OFFSET ?", []any{20, 2, 1}},
		{"SELECT count(*) FROM `users` WHERE `users`.`deleted_at` IS NULL", nil},
		{"SELECT count(*) FROM `users` WHERE age >= ? AND `users`.`deleted_at` IS NULL", []any{40}},
		// Pluck / Distinct / Group / Having, as the builder emits them.
		{"SELECT `name` FROM `users` WHERE `users`.`deleted_at` IS NULL ORDER BY `name`", nil},
		{"SELECT DISTINCT `company_id` FROM `users` WHERE `users`.`deleted_at` IS NULL ORDER BY `company_id`", nil},
		{"SELECT company_id,count(*) AS n FROM `users` WHERE `users`.`deleted_at` IS NULL GROUP BY `company_id` HAVING count(*) > ? ORDER BY `company_id`", []any{1}},
		// Preload: the IN-list over collected foreign keys.
		{"SELECT * FROM `companies` WHERE `companies`.`id` IN (?,?) AND `companies`.`deleted_at` IS NULL", []any{1, 1}},
		// Joins.
		{"SELECT `users`.`name`,`companies`.`name` FROM `users` LEFT JOIN `companies` ON `users`.`company_id` = `companies`.`id` WHERE `users`.`deleted_at` IS NULL ORDER BY `users`.`id`", nil},
		// Save / Updates, and the soft DELETE that is really an UPDATE.
		{"UPDATE `users` SET `updated_at`=?,`age`=? WHERE `users`.`deleted_at` IS NULL AND `id` = ?", []any{"2024-02-01 00:00:00", 31, 1}},
		{"UPDATE `users` SET `deleted_at`=? WHERE `users`.`id` = ? AND `users`.`deleted_at` IS NULL", []any{"2024-02-02 00:00:00", 2}},
		{"SELECT count(*) FROM `users` WHERE `users`.`deleted_at` IS NULL", nil},
		{"SELECT count(*) FROM `users`", nil},
		// Unscoped hard delete.
		{"DELETE FROM `users` WHERE `users`.`id` = ?", []any{4}},
		// Upsert: clause.OnConflict{Columns, DoUpdates}, which is what
		// FirstOrCreate and Save-on-conflict emit.
		{"INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`email`,`company_id`) VALUES (?,?,?,?,?,?,?) ON CONFLICT (`email`) DO UPDATE SET `name`=`excluded`.`name`,`age`=`excluded`.`age`,`updated_at`=`excluded`.`updated_at` RETURNING `id`", []any{"2024-03-01 00:00:00", "2024-03-01 00:00:00", nil, "alice2", 33, "a@x", 1}},
		{"INSERT INTO `users` (`created_at`,`updated_at`,`deleted_at`,`name`,`age`,`email`,`company_id`) VALUES (?,?,?,?,?,?,?) ON CONFLICT DO NOTHING", []any{"2024-03-02 00:00:00", "2024-03-02 00:00:00", nil, "alice3", 34, "a@x", 1}},
		{"SELECT `id`,`name`,`age`,`email` FROM `users` ORDER BY `id`", nil},
		// A subquery condition and an EXISTS, both of which the builder emits.
		{"SELECT * FROM `users` WHERE `company_id` IN (SELECT `id` FROM `companies` WHERE `name` = ?) AND `users`.`deleted_at` IS NULL ORDER BY `id`", []any{"Acme"}},
		{"SELECT * FROM `companies` WHERE EXISTS (SELECT 1 FROM `users` WHERE `users`.`company_id` = `companies`.`id` AND `users`.`deleted_at` IS NULL)", nil},
		// Migrator: a column added and dropped, and a renamed table.
		{"ALTER TABLE `users` ADD `nickname` text", nil},
		{"ALTER TABLE `users` DROP COLUMN `nickname`", nil},
		{"ALTER TABLE `companies` RENAME TO `orgs`", nil},
		{"SELECT sql FROM sqlite_master WHERE type='table' AND name='users'", nil},
		{"DROP TABLE `users`", nil},
		{"DROP TABLE `orgs`", nil},
	})
}

// TestEntGeneratedSQL is Ent's SQLite dialect: it brackets a migration with
// "PRAGMA foreign_keys = off"/"on", names every constraint, and uses an edge
// (join) table for M2M. Its introspection reads sqlite_master with bound
// parameters.
func TestEntGeneratedSQL(t *testing.T) {
	runORMScript(t, "ent", []ormStep{
		{`PRAGMA foreign_keys = off`, nil},
		{"SELECT `name`, `type`, `sql` FROM sqlite_master WHERE `type` = ? AND `name` <> ?", []any{"table", "sqlite_sequence"}},
		{"CREATE TABLE `users` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `age` integer NOT NULL, `name` text NOT NULL DEFAULT 'unknown', `nickname` text NULL, `created_at` datetime NOT NULL)", nil},
		{"CREATE UNIQUE INDEX `users_nickname_key` ON `users` (`nickname`)", nil},
		{"CREATE TABLE `groups` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `name` text NOT NULL)", nil},
		{"CREATE TABLE `group_users` (`group_id` integer NOT NULL, `user_id` integer NOT NULL, PRIMARY KEY (`group_id`, `user_id`), CONSTRAINT `group_users_group_id` FOREIGN KEY (`group_id`) REFERENCES `groups` (`id`) ON DELETE CASCADE, CONSTRAINT `group_users_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE)", nil},
		{"CREATE TABLE `posts` (`id` integer NOT NULL PRIMARY KEY AUTOINCREMENT, `title` text NOT NULL, `user_posts` integer NULL, CONSTRAINT `posts_users_posts` FOREIGN KEY (`user_posts`) REFERENCES `users` (`id`) ON DELETE SET NULL)", nil},
		{"CREATE INDEX `post_title` ON `posts` (`title`)", nil},
		{`PRAGMA foreign_keys = on`, nil},
		// Ent's own table_info introspection, which it uses to diff the schema.
		{"PRAGMA table_info(`users`)", nil},
		{"PRAGMA index_list(`users`)", nil},
		{"PRAGMA foreign_key_list(`group_users`)", nil},
		// Create, Ent style: explicit column list, then LastInsertId.
		{"INSERT INTO `users` (`age`, `name`, `nickname`, `created_at`) VALUES (?, ?, ?, ?)", []any{30, "alice", "al", "2024-01-01 00:00:00"}},
		{"INSERT INTO `users` (`age`, `name`, `nickname`, `created_at`) VALUES (?, ?, ?, ?)", []any{40, "bob", nil, "2024-01-02 00:00:00"}},
		{"INSERT INTO `users` (`age`, `name`, `nickname`, `created_at`) VALUES (?, ?, ?, ?)", []any{50, "carol", nil, "2024-01-03 00:00:00"}},
		{"INSERT INTO `groups` (`name`) VALUES (?)", []any{"admins"}},
		{"INSERT INTO `group_users` (`group_id`, `user_id`) VALUES (?, ?), (?, ?)", []any{1, 1, 1, 2}},
		{"INSERT INTO `posts` (`title`, `user_posts`) VALUES (?, ?)", []any{"hello", 1}},
		// Query: Ent's generated SELECT quotes every column and table.
		{"SELECT `users`.`id`, `users`.`age`, `users`.`name`, `users`.`nickname` FROM `users` WHERE `users`.`age` > ? ORDER BY `users`.`id` LIMIT ?", []any{20, 2}},
		{"SELECT `users`.`id`, `users`.`name` FROM `users` WHERE `users`.`name` IN (?, ?) ORDER BY `users`.`id`", []any{"alice", "carol"}},
		{"SELECT COUNT(*) FROM `users` WHERE `users`.`age` >= ?", []any{40}},
		// The M2M traversal Ent emits: a join through the edge table.
		{"SELECT DISTINCT `users`.`id`, `users`.`name` FROM `users` JOIN (SELECT `group_users`.`user_id` FROM `group_users` WHERE `group_users`.`group_id` = ?) AS `t1` ON `users`.`id` = `t1`.`user_id` ORDER BY `users`.`id`", []any{1}},
		// The O2M eager load: an IN over collected ids.
		{"SELECT `posts`.`id`, `posts`.`title`, `posts`.`user_posts` FROM `posts` WHERE `posts`.`user_posts` IN (?, ?)", []any{1, 2}},
		// Ent's GroupBy/Aggregate.
		{"SELECT `users`.`age`, COUNT(*) AS `count` FROM `users` GROUP BY `users`.`age` ORDER BY `users`.`age`", nil},
		{"SELECT MAX(`users`.`age`) AS `max`, MIN(`users`.`age`) AS `min`, SUM(`users`.`age`) AS `sum`, AVG(`users`.`age`) AS `avg` FROM `users`", nil},
		// Update / UpdateOne, including Ent's "add" form for numeric fields.
		{"UPDATE `users` SET `name` = ?, `age` = COALESCE(`users`.`age`, ?) + ? WHERE `users`.`id` = ?", []any{"alice!", 0, 5, 1}},
		{"UPDATE `users` SET `nickname` = NULL WHERE `users`.`id` = ?", []any{1}},
		{"SELECT `id`, `name`, `age`, `nickname` FROM `users` ORDER BY `id`", nil},
		// Upsert (ent's OnConflict), with the sqlite spelling it emits.
		{"INSERT INTO `groups` (`name`) VALUES (?) ON CONFLICT DO UPDATE SET `name` = `excluded`.`name`", []any{"admins2"}},
		// Delete, and the FK cascade the edge table declares.
		{"DELETE FROM `users` WHERE `users`.`id` = ?", []any{2}},
		{"SELECT `group_id`, `user_id` FROM `group_users` ORDER BY 1,2", nil},
		{"DELETE FROM `users` WHERE `users`.`id` = ?", []any{1}},
		{"SELECT `id`, `title`, `user_posts` FROM `posts` ORDER BY `id`", nil},
		{`PRAGMA foreign_key_check`, nil},
		{`PRAGMA integrity_check`, nil},
	})
}

// TestSqlcStyleQueries is the hand-written-SQL shape sqlc compiles: named
// parameters, RETURNING on every mutation, and the CTE/window queries people
// actually put in a .sql file.
func TestSqlcStyleQueries(t *testing.T) {
	runORMScript(t, "sqlc", []ormStep{
		{`CREATE TABLE authors (id INTEGER PRIMARY KEY, name text NOT NULL, bio text)`, nil},
		{`CREATE TABLE books (id INTEGER PRIMARY KEY, author_id INTEGER NOT NULL REFERENCES authors(id), title text NOT NULL, published INTEGER, price REAL)`, nil},
		{`CREATE INDEX books_author_id ON books (author_id)`, nil},
		// CreateAuthor :one
		{`INSERT INTO authors (name, bio) VALUES (?, ?) RETURNING id, name, bio`, []any{"Ann", "writes"}},
		{`INSERT INTO authors (name, bio) VALUES (?, ?) RETURNING id, name, bio`, []any{"Ben", nil}},
		{`INSERT INTO books (author_id, title, published, price) VALUES (?,?,?,?) RETURNING *`, []any{1, "One", 2001, 9.99}},
		{`INSERT INTO books (author_id, title, published, price) VALUES (?,?,?,?) RETURNING *`, []any{1, "Two", 2002, 19.5}},
		{`INSERT INTO books (author_id, title, published, price) VALUES (?,?,?,?) RETURNING *`, []any{2, "Three", 2003, nil}},
		// GetAuthor :one / ListAuthors :many
		{`SELECT id, name, bio FROM authors WHERE id = ?`, []any{1}},
		{`SELECT id, name, bio FROM authors ORDER BY name`, nil},
		// A paginated list, which is the shape a cached plan can get wrong.
		{`SELECT id, title FROM books ORDER BY id LIMIT ? OFFSET ?`, []any{2, 0}},
		{`SELECT id, title FROM books ORDER BY id LIMIT ? OFFSET ?`, []any{2, 2}},
		{`SELECT id, title FROM books ORDER BY id LIMIT ? OFFSET ?`, []any{1, 1}},
		// Aggregates and a join, with sqlc's COALESCE-for-not-null idiom.
		{`SELECT a.id, a.name, COALESCE(count(b.id), 0) AS books FROM authors a LEFT JOIN books b ON b.author_id = a.id GROUP BY a.id, a.name ORDER BY a.id`, nil},
		{`SELECT COALESCE(sum(price), 0.0) AS total, COALESCE(avg(price), 0.0) AS mean FROM books`, nil},
		// A CTE and a window function, both common in a .sql file.
		{`WITH ranked AS (SELECT id, title, price, row_number() OVER (PARTITION BY author_id ORDER BY price DESC NULLS LAST) AS rn FROM books) SELECT id, title FROM ranked WHERE rn = 1 ORDER BY id`, nil},
		{`WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n+1 FROM seq WHERE n < ?) SELECT count(*) FROM seq`, []any{10}},
		// Named parameters, which sqlc emits for repeated use of one value.
		{`SELECT id, title FROM books WHERE (:q IS NULL OR title LIKE '%' || :q || '%') ORDER BY id`, []any{namedArg("q", "T")}},
		{`SELECT id, title FROM books WHERE (:q IS NULL OR title LIKE '%' || :q || '%') ORDER BY id`, []any{namedArg("q", nil)}},
		// UpdateAuthor :exec / :one, and a DELETE ... RETURNING.
		{`UPDATE authors SET name = ?, bio = ? WHERE id = ? RETURNING id, name, bio`, []any{"Ann B", "still writes", 1}},
		{`UPDATE books SET price = price * ? WHERE author_id = ? RETURNING id, price`, []any{2, 1}},
		{`DELETE FROM books WHERE id = ? RETURNING id, title`, []any{1}},
		{`DELETE FROM authors WHERE id = ? RETURNING id`, []any{99}},
		{`SELECT id, title, price FROM books ORDER BY id`, nil},
		// The json a modern query set often returns.
		{`SELECT json_group_array(json_object('id', id, 'title', title)) FROM books`, nil},
		// An IN over a variadic list, which sqlc expands to the exact arity.
		{`SELECT id, title FROM books WHERE id IN (?, ?, ?) ORDER BY id`, []any{1, 2, 3}},
		{`SELECT count(*) FROM books WHERE published BETWEEN ? AND ?`, []any{2001, 2002}},
		{`PRAGMA foreign_key_check`, nil},
	})
}

// normalizeDeclTypeTimes rewrites the way a Go time.Time renders back into the
// text SQLite stored, so a "datetime" column's cell compares as SQL. See
// ormRows for what this is papering over and why it is legitimate HERE and
// nowhere else.
func normalizeDeclTypeTimes(s string) string {
	return strings.ReplaceAll(s, " +0000 UTC", "")
}

// TestDatetimeDeclTypeIsTextNotTime pins the driver-level difference
// normalizeDeclTypeTimes papers over, so it is a recorded fact rather than a
// hidden one: scanning a "datetime" column into a Go time.Time WORKS through
// mattn and FAILS through this driver, because mattn parses the text for three
// declared type names and this driver does not.
//
// SQLite has no date type -- the value on disk is TEXT either way, and every
// SQL-level comparison in this file agrees. What differs is the Go value
// database/sql is handed, and an ORM whose model declares a time.Time field
// meets it immediately.
func TestDatetimeDeclTypeIsTextNotTime(t *testing.T) {
	for _, decl := range []string{"datetime", "timestamp", "date", "DATETIME", "text"} {
		decl := decl
		t.Run(decl, func(t *testing.T) {
			c, m := boundPair(t, []string{
				fmt.Sprintf(`CREATE TABLE t(id INTEGER PRIMARY KEY, at %s)`, decl),
				`INSERT INTO t VALUES(1, '2024-02-29 13:45:56')`,
			})
			var got [2]string
			for i, db := range [2]*sql.DB{c, m} {
				var tv time.Time
				err := db.QueryRow(`SELECT at FROM t WHERE id = 1`).Scan(&tv)
				if err != nil {
					got[i] = "ERR"
					continue
				}
				got[i] = tv.UTC().Format("2006-01-02 15:04:05")
			}
			// "text" is the control: neither driver converts it, so both fail.
			wantCgo := "2024-02-29 13:45:56"
			if strings.EqualFold(decl, "text") {
				wantCgo = "ERR"
			}
			if got[0] != wantCgo {
				t.Errorf("cgo scanned %q into time.Time, want %q -- mattn's decltype list may have changed", got[0], wantCgo)
			}
			if got[1] != "ERR" {
				t.Errorf("this driver now converts a %s column to time.Time (%q) -- if that is intended, the ORM sweep's normalizeDeclTypeTimes and this pin both go away", decl, got[1])
			}
		})
	}
}

// namedArg is sql.Named, kept short because the sqlc shapes use it repeatedly.
func namedArg(name string, v any) any { return sql.Named(name, v) }
