package compat

import "testing"

// TestSqliteSequenceIsARealTable pins sqlite_sequence as an ordinary table
// that each INSERT statement reads at its start and writes at its end
// (sqlite3AutoincrementBegin/End, insert.c:460-575): its rows are the user's
// to change, the FIRST row naming a table wins, and a statement that inserts
// nothing still leaves a (name, 0) row.
func TestSqliteSequenceIsARealTable(t *testing.T) {
	differ(t, "sqlite_sequence direct writes", []string{
		"CREATE TABLE t1(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"SELECT * FROM sqlite_sequence",
		"INSERT INTO t1(b) VALUES('x'),('y')",
		"SELECT * FROM sqlite_sequence",
		"UPDATE sqlite_sequence SET seq=100 WHERE name='t1'",
		"INSERT INTO t1(b) VALUES('z')",
		"SELECT a FROM t1 ORDER BY a",
		"DELETE FROM sqlite_sequence WHERE name='t1'",
		"DELETE FROM t1",
		"INSERT INTO t1(b) VALUES('w')",
		"SELECT a FROM t1 ORDER BY a",
		"SELECT rowid, * FROM sqlite_sequence",
		"INSERT INTO sqlite_sequence VALUES('t1', 500)",
		"INSERT INTO t1(b) VALUES('v')",
		"SELECT a FROM t1 ORDER BY a",
		"SELECT rowid, * FROM sqlite_sequence",
		"INSERT INTO sqlite_sequence VALUES('extra', 999)",
		"SELECT rowid, * FROM sqlite_sequence",
		"UPDATE sqlite_sequence SET seq='7' WHERE rowid=1",
		"INSERT INTO t1(b) VALUES('u')",
		"SELECT rowid, name, seq, typeof(seq) FROM sqlite_sequence",
		"UPDATE sqlite_sequence SET seq=20.5 WHERE rowid=1",
		"INSERT INTO t1(b) VALUES('s')",
		"SELECT rowid, name, seq, typeof(seq) FROM sqlite_sequence",
		"UPDATE sqlite_sequence SET name='T1' WHERE rowid=1",
		"INSERT INTO t1(b) VALUES('r')",
		"SELECT rowid, name, seq FROM sqlite_sequence",
		"SELECT a FROM t1 ORDER BY a",
	})
	differ(t, "sqlite_sequence statement-level rules", []string{
		"CREATE TABLE t2(x)",
		"CREATE TABLE t3(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"INSERT INTO t3 SELECT * FROM t2 WHERE 0",
		"SELECT * FROM sqlite_sequence",
		"INSERT INTO t3 VALUES(50, 'a')",
		"INSERT OR IGNORE INTO t3 VALUES(50, 'dup')",
		"DELETE FROM t3 WHERE a=50",
		"INSERT INTO t3 VALUES(10, 'b')",
		"INSERT OR IGNORE INTO t3 VALUES(10, 'c'), (80, 'd')",
		"DELETE FROM t3 WHERE a=80",
		"INSERT INTO t3(b) VALUES('e')",
		"SELECT a, b FROM t3 ORDER BY a",
		"SELECT * FROM sqlite_sequence",
		"UPDATE t3 SET a=200 WHERE b='e'",
		"SELECT * FROM sqlite_sequence",
		"DELETE FROM t3 WHERE a=200",
		"INSERT INTO t3(b) VALUES('f')",
		"SELECT a, b FROM t3 ORDER BY a",
		"INSERT INTO t3 VALUES(-5, 'neg')",
		"SELECT * FROM sqlite_sequence",
		"CREATE TABLE u(k UNIQUE ON CONFLICT FAIL)",
		"CREATE TABLE t4(a INTEGER PRIMARY KEY AUTOINCREMENT, k UNIQUE ON CONFLICT FAIL)",
		"INSERT INTO t4(k) VALUES(1)",
		"INSERT INTO t4(k) VALUES(2),(3),(1),(4)",
		"SELECT a, k FROM t4 ORDER BY a",
		"SELECT * FROM sqlite_sequence ORDER BY name",
		"BEGIN",
		"INSERT INTO t4(k) VALUES(9)",
		"SELECT * FROM sqlite_sequence ORDER BY name",
		"ROLLBACK",
		"SELECT * FROM sqlite_sequence ORDER BY name",
		"REPLACE INTO t4(a, k) VALUES(7, 2)",
		"SELECT a, k FROM t4 ORDER BY a",
		"SELECT * FROM sqlite_sequence ORDER BY name",
		"INSERT INTO t4(k) VALUES(5) RETURNING a",
		"INSERT INTO t4(a, k) VALUES(1, 6) ON CONFLICT(a) DO UPDATE SET k=66",
		"INSERT INTO t4(a, k) VALUES(300, 3) ON CONFLICT(k) DO UPDATE SET k=33",
		"SELECT a, k FROM t4 ORDER BY a",
		"SELECT * FROM sqlite_sequence ORDER BY name",
	})
	differ(t, "sqlite_sequence through triggers", []string{
		"CREATE TABLE s1(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"CREATE TABLE s2(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"CREATE TABLE s3(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"CREATE TABLE plain(x)",
		"CREATE TRIGGER r1 AFTER INSERT ON s1 BEGIN INSERT INTO s2(b) VALUES(new.b); END",
		"CREATE TRIGGER r2 BEFORE INSERT ON s2 BEGIN INSERT INTO s3(b) VALUES(new.b); END",
		"INSERT INTO s1(b) VALUES('one')",
		"SELECT rowid, * FROM sqlite_sequence",
		"CREATE TRIGGER r3 AFTER UPDATE ON plain BEGIN INSERT INTO s3(b) SELECT 1 WHERE 0; END",
		"INSERT INTO plain VALUES(1)",
		"UPDATE plain SET x=2 WHERE 0",
		"SELECT rowid, * FROM sqlite_sequence",
		"CREATE TABLE s4(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"CREATE TRIGGER r4 AFTER DELETE ON plain BEGIN INSERT INTO s4(b) VALUES(old.x); END",
		"DELETE FROM plain WHERE 0",
		"SELECT rowid, * FROM sqlite_sequence",
		"DELETE FROM plain",
		"SELECT rowid, * FROM sqlite_sequence",
		"CREATE TRIGGER r5 AFTER INSERT ON s4 BEGIN DELETE FROM sqlite_sequence WHERE name='s4'; END",
		"INSERT INTO s4(b) VALUES('x'), ('y')",
		"SELECT rowid, * FROM sqlite_sequence",
		"SELECT a, b FROM s4 ORDER BY a",
	})
	differ(t, "sqlite_sequence across DDL", []string{
		"CREATE TABLE d1(a INTEGER PRIMARY KEY AUTOINCREMENT, b UNIQUE)",
		"SELECT type, name, tbl_name, sql FROM sqlite_schema ORDER BY rowid",
		"INSERT INTO d1(b) VALUES(1),(2)",
		"CREATE TABLE d2(a INTEGER PRIMARY KEY AUTOINCREMENT)",
		"INSERT INTO d2 VALUES(NULL)",
		"SELECT * FROM sqlite_sequence",
		"ALTER TABLE d1 RENAME TO d1x",
		"SELECT * FROM sqlite_sequence",
		"DROP TABLE d1x",
		"SELECT * FROM sqlite_sequence",
		"CREATE TABLE d1x(a INTEGER PRIMARY KEY AUTOINCREMENT)",
		"INSERT INTO d1x VALUES(NULL)",
		"SELECT * FROM d1x",
		"SELECT rowid, * FROM sqlite_sequence",
		"DROP TABLE sqlite_sequence",
		"CREATE INDEX i ON sqlite_sequence(name)",
		"CREATE TEMP TABLE tt(a INTEGER PRIMARY KEY AUTOINCREMENT, b)",
		"INSERT INTO tt(b) VALUES('t')",
		"SELECT * FROM temp.sqlite_sequence",
		"SELECT * FROM main.sqlite_sequence",
		"SELECT type, name FROM temp.sqlite_schema ORDER BY rowid",
		"DROP TABLE tt",
		"SELECT * FROM temp.sqlite_sequence",
		"VACUUM",
		"SELECT rowid, * FROM sqlite_sequence",
		"INSERT INTO d2 VALUES(9223372036854775807)",
		"INSERT INTO d2 VALUES(NULL)",
		"SELECT * FROM sqlite_sequence",
		"PRAGMA integrity_check",
	})
}
