// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: transport.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Cell represents a single column value in an operation.
type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Col           string                 `protobuf:"bytes,1,opt,name=col,proto3" json:"col,omitempty"`
	Type          uint32                 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Val           []byte                 `protobuf:"bytes,3,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_transport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{0}
}

func (x *Cell) GetCol() string {
	if x != nil {
		return x.Col
	}
	return ""
}

func (x *Cell) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Cell) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

// Op represents a single operation (Insert/Update/Delete) captured from the database.
type Op struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	Hlc           uint64                 `protobuf:"varint,3,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Tbl           string                 `protobuf:"bytes,4,opt,name=tbl,proto3" json:"tbl,omitempty"`
	Pk            []byte                 `protobuf:"bytes,5,opt,name=pk,proto3" json:"pk,omitempty"`
	Kind          uint32                 `protobuf:"varint,6,opt,name=kind,proto3" json:"kind,omitempty"`
	Cells         []*Cell                `protobuf:"bytes,7,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Op) Reset() {
	*x = Op{}
	mi := &file_transport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Op) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Op) ProtoMessage() {}

func (x *Op) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Op.ProtoReflect.Descriptor instead.
func (*Op) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{1}
}

func (x *Op) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Op) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Op) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *Op) GetTbl() string {
	if x != nil {
		return x.Tbl
	}
	return ""
}

func (x *Op) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *Op) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Op) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

// VVEntry is one (site, seq) pair of a version vector.
type VVEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Seq           uint64                 `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VVEntry) Reset() {
	*x = VVEntry{}
	mi := &file_transport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VVEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VVEntry) ProtoMessage() {}

func (x *VVEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VVEntry.ProtoReflect.Descriptor instead.
func (*VVEntry) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{2}
}

func (x *VVEntry) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *VVEntry) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// ExchangeVVRequest carries the caller's local version vector.
type ExchangeVVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vv            []*VVEntry             `protobuf:"bytes,1,rep,name=vv,proto3" json:"vv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeVVRequest) Reset() {
	*x = ExchangeVVRequest{}
	mi := &file_transport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeVVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeVVRequest) ProtoMessage() {}

func (x *ExchangeVVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeVVRequest.ProtoReflect.Descriptor instead.
func (*ExchangeVVRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{3}
}

func (x *ExchangeVVRequest) GetVv() []*VVEntry {
	if x != nil {
		return x.Vv
	}
	return nil
}

// ExchangeVVResponse carries the responder's local version vector.
type ExchangeVVResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vv            []*VVEntry             `protobuf:"bytes,1,rep,name=vv,proto3" json:"vv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeVVResponse) Reset() {
	*x = ExchangeVVResponse{}
	mi := &file_transport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeVVResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeVVResponse) ProtoMessage() {}

func (x *ExchangeVVResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeVVResponse.ProtoReflect.Descriptor instead.
func (*ExchangeVVResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{4}
}

func (x *ExchangeVVResponse) GetVv() []*VVEntry {
	if x != nil {
		return x.Vv
	}
	return nil
}

// GetOpsRequest asks for ops from a given site after fromSeq, capped at limit.
type GetOpsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	FromSeq       uint64                 `protobuf:"varint,2,opt,name=from_seq,json=fromSeq,proto3" json:"from_seq,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpsRequest) Reset() {
	*x = GetOpsRequest{}
	mi := &file_transport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpsRequest) ProtoMessage() {}

func (x *GetOpsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpsRequest.ProtoReflect.Descriptor instead.
func (*GetOpsRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{5}
}

func (x *GetOpsRequest) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *GetOpsRequest) GetFromSeq() uint64 {
	if x != nil {
		return x.FromSeq
	}
	return 0
}

func (x *GetOpsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// GetOpsResponse carries the requested ops, or pruned: the responder no
// longer holds them (replication.ErrPruned), and a snapshot is needed.
type GetOpsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*Op                  `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	Pruned        bool                   `protobuf:"varint,2,opt,name=pruned,proto3" json:"pruned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpsResponse) Reset() {
	*x = GetOpsResponse{}
	mi := &file_transport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpsResponse) ProtoMessage() {}

func (x *GetOpsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpsResponse.ProtoReflect.Descriptor instead.
func (*GetOpsResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{6}
}

func (x *GetOpsResponse) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *GetOpsResponse) GetPruned() bool {
	if x != nil {
		return x.Pruned
	}
	return false
}

// AckEntry is one site's ack: its version vector, stamped by its clock.
type AckEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Hlc           uint64                 `protobuf:"varint,2,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Vv            []*VVEntry             `protobuf:"bytes,3,rep,name=vv,proto3" json:"vv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckEntry) Reset() {
	*x = AckEntry{}
	mi := &file_transport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckEntry) ProtoMessage() {}

func (x *AckEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckEntry.ProtoReflect.Descriptor instead.
func (*AckEntry) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{7}
}

func (x *AckEntry) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *AckEntry) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *AckEntry) GetVv() []*VVEntry {
	if x != nil {
		return x.Vv
	}
	return nil
}

// ExchangeAcksRequest carries the acks the caller knows; the response, the
// responder's.
type ExchangeAcksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*AckEntry            `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAcksRequest) Reset() {
	*x = ExchangeAcksRequest{}
	mi := &file_transport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAcksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAcksRequest) ProtoMessage() {}

func (x *ExchangeAcksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAcksRequest.ProtoReflect.Descriptor instead.
func (*ExchangeAcksRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{8}
}

func (x *ExchangeAcksRequest) GetAcks() []*AckEntry {
	if x != nil {
		return x.Acks
	}
	return nil
}

type ExchangeAcksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*AckEntry            `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExchangeAcksResponse) Reset() {
	*x = ExchangeAcksResponse{}
	mi := &file_transport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExchangeAcksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExchangeAcksResponse) ProtoMessage() {}

func (x *ExchangeAcksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExchangeAcksResponse.ProtoReflect.Descriptor instead.
func (*ExchangeAcksResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{9}
}

func (x *ExchangeAcksResponse) GetAcks() []*AckEntry {
	if x != nil {
		return x.Acks
	}
	return nil
}

// ClockCell is one _repl_clock row.
type ClockCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tbl           string                 `protobuf:"bytes,1,opt,name=tbl,proto3" json:"tbl,omitempty"`
	Pk            []byte                 `protobuf:"bytes,2,opt,name=pk,proto3" json:"pk,omitempty"`
	Col           string                 `protobuf:"bytes,3,opt,name=col,proto3" json:"col,omitempty"`
	Hlc           uint64                 `protobuf:"varint,4,opt,name=hlc,proto3" json:"hlc,omitempty"`
	Site          string                 `protobuf:"bytes,5,opt,name=site,proto3" json:"site,omitempty"`
	Val           []byte                 `protobuf:"bytes,6,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClockCell) Reset() {
	*x = ClockCell{}
	mi := &file_transport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClockCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClockCell) ProtoMessage() {}

func (x *ClockCell) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClockCell.ProtoReflect.Descriptor instead.
func (*ClockCell) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{10}
}

func (x *ClockCell) GetTbl() string {
	if x != nil {
		return x.Tbl
	}
	return ""
}

func (x *ClockCell) GetPk() []byte {
	if x != nil {
		return x.Pk
	}
	return nil
}

func (x *ClockCell) GetCol() string {
	if x != nil {
		return x.Col
	}
	return ""
}

func (x *ClockCell) GetHlc() uint64 {
	if x != nil {
		return x.Hlc
	}
	return 0
}

func (x *ClockCell) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ClockCell) GetVal() []byte {
	if x != nil {
		return x.Val
	}
	return nil
}

// RangeEntry is a rowid range's owner: site, and the range's lo.
type RangeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Site          string                 `protobuf:"bytes,1,opt,name=site,proto3" json:"site,omitempty"`
	Lo            uint64                 `protobuf:"varint,2,opt,name=lo,proto3" json:"lo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RangeEntry) Reset() {
	*x = RangeEntry{}
	mi := &file_transport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RangeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeEntry) ProtoMessage() {}

func (x *RangeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeEntry.ProtoReflect.Descriptor instead.
func (*RangeEntry) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{11}
}

func (x *RangeEntry) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *RangeEntry) GetLo() uint64 {
	if x != nil {
		return x.Lo
	}
	return 0
}

// GetSnapshotRequest asks for one page of a part of the responder's snapshot.
type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Part          uint32                 `protobuf:"varint,1,opt,name=part,proto3" json:"part,omitempty"`
	Cursor        []byte                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_transport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{12}
}

func (x *GetSnapshotRequest) GetPart() uint32 {
	if x != nil {
		return x.Part
	}
	return 0
}

func (x *GetSnapshotRequest) GetCursor() []byte {
	if x != nil {
		return x.Cursor
	}
	return nil
}

// GetSnapshotResponse is that page; next is empty after the part's last.
type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ops           []*Op                  `protobuf:"bytes,1,rep,name=ops,proto3" json:"ops,omitempty"`
	Floors        []*VVEntry             `protobuf:"bytes,2,rep,name=floors,proto3" json:"floors,omitempty"`
	Ranges        []*RangeEntry          `protobuf:"bytes,3,rep,name=ranges,proto3" json:"ranges,omitempty"`
	Cells         []*ClockCell           `protobuf:"bytes,4,rep,name=cells,proto3" json:"cells,omitempty"`
	Next          []byte                 `protobuf:"bytes,5,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_transport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{13}
}

func (x *GetSnapshotResponse) GetOps() []*Op {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *GetSnapshotResponse) GetFloors() []*VVEntry {
	if x != nil {
		return x.Floors
	}
	return nil
}

func (x *GetSnapshotResponse) GetRanges() []*RangeEntry {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *GetSnapshotResponse) GetCells() []*ClockCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

func (x *GetSnapshotResponse) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

// PushMessage carries a single pushed op, published over gossipsub.
type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            *Op                    `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_transport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{14}
}

func (x *PushMessage) GetOp() *Op {
	if x != nil {
		return x.Op
	}
	return nil
}

// Request is the one message a request/response stream carries from the caller.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Request_ExchangeVv
	//	*Request_GetOps
	//	*Request_GetSnapshot
	//	*Request_ExchangeAcks
	Msg           isRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_transport_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{15}
}

func (x *Request) GetMsg() isRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Request) GetExchangeVv() *ExchangeVVRequest {
	if x != nil {
		if x, ok := x.Msg.(*Request_ExchangeVv); ok {
			return x.ExchangeVv
		}
	}
	return nil
}

func (x *Request) GetGetOps() *GetOpsRequest {
	if x != nil {
		if x, ok := x.Msg.(*Request_GetOps); ok {
			return x.GetOps
		}
	}
	return nil
}

func (x *Request) GetGetSnapshot() *GetSnapshotRequest {
	if x != nil {
		if x, ok := x.Msg.(*Request_GetSnapshot); ok {
			return x.GetSnapshot
		}
	}
	return nil
}

func (x *Request) GetExchangeAcks() *ExchangeAcksRequest {
	if x != nil {
		if x, ok := x.Msg.(*Request_ExchangeAcks); ok {
			return x.ExchangeAcks
		}
	}
	return nil
}

type isRequest_Msg interface {
	isRequest_Msg()
}

type Request_ExchangeVv struct {
	ExchangeVv *ExchangeVVRequest `protobuf:"bytes,1,opt,name=exchange_vv,json=exchangeVv,proto3,oneof"`
}

type Request_GetOps struct {
	GetOps *GetOpsRequest `protobuf:"bytes,2,opt,name=get_ops,json=getOps,proto3,oneof"`
}

type Request_GetSnapshot struct {
	GetSnapshot *GetSnapshotRequest `protobuf:"bytes,3,opt,name=get_snapshot,json=getSnapshot,proto3,oneof"`
}

type Request_ExchangeAcks struct {
	ExchangeAcks *ExchangeAcksRequest `protobuf:"bytes,4,opt,name=exchange_acks,json=exchangeAcks,proto3,oneof"`
}

func (*Request_ExchangeVv) isRequest_Msg() {}

func (*Request_GetOps) isRequest_Msg() {}

func (*Request_GetSnapshot) isRequest_Msg() {}

func (*Request_ExchangeAcks) isRequest_Msg() {}

// Response is the one message the responder answers a Request with.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Response_ExchangeVv
	//	*Response_GetOps
	//	*Response_GetSnapshot
	//	*Response_ExchangeAcks
	Msg           isResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_transport_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_transport_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_transport_proto_rawDescGZIP(), []int{16}
}

func (x *Response) GetMsg() isResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Response) GetExchangeVv() *ExchangeVVResponse {
	if x != nil {
		if x, ok := x.Msg.(*Response_ExchangeVv); ok {
			return x.ExchangeVv
		}
	}
	return nil
}

func (x *Response) GetGetOps() *GetOpsResponse {
	if x != nil {
		if x, ok := x.Msg.(*Response_GetOps); ok {
			return x.GetOps
		}
	}
	return nil
}

func (x *Response) GetGetSnapshot() *GetSnapshotResponse {
	if x != nil {
		if x, ok := x.Msg.(*Response_GetSnapshot); ok {
			return x.GetSnapshot
		}
	}
	return nil
}

func (x *Response) GetExchangeAcks() *ExchangeAcksResponse {
	if x != nil {
		if x, ok := x.Msg.(*Response_ExchangeAcks); ok {
			return x.ExchangeAcks
		}
	}
	return nil
}

type isResponse_Msg interface {
	isResponse_Msg()
}

type Response_ExchangeVv struct {
	ExchangeVv *ExchangeVVResponse `protobuf:"bytes,1,opt,name=exchange_vv,json=exchangeVv,proto3,oneof"`
}

type Response_GetOps struct {
	GetOps *GetOpsResponse `protobuf:"bytes,2,opt,name=get_ops,json=getOps,proto3,oneof"`
}

type Response_GetSnapshot struct {
	GetSnapshot *GetSnapshotResponse `protobuf:"bytes,3,opt,name=get_snapshot,json=getSnapshot,proto3,oneof"`
}

type Response_ExchangeAcks struct {
	ExchangeAcks *ExchangeAcksResponse `protobuf:"bytes,4,opt,name=exchange_acks,json=exchangeAcks,proto3,oneof"`
}

func (*Response_ExchangeVv) isResponse_Msg() {}

func (*Response_GetOps) isResponse_Msg() {}

func (*Response_GetSnapshot) isResponse_Msg() {}

func (*Response_ExchangeAcks) isResponse_Msg() {}

var File_transport_proto protoreflect.FileDescriptor

const file_transport_proto_rawDesc = "" +
	"\n" +
	"\x0ftransport.proto\x12\rreplicationpb\">\n" +
	"\x04Cell\x12\x10\n" +
	"\x03col\x18\x01 \x01(\tR\x03col\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12\x10\n" +
	"\x03val\x18\x03 \x01(\fR\x03val\"\x9d\x01\n" +
	"\x02Op\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\x12\x10\n" +
	"\x03hlc\x18\x03 \x01(\x04R\x03hlc\x12\x10\n" +
	"\x03tbl\x18\x04 \x01(\tR\x03tbl\x12\x0e\n" +
	"\x02pk\x18\x05 \x01(\fR\x02pk\x12\x12\n" +
	"\x04kind\x18\x06 \x01(\rR\x04kind\x12)\n" +
	"\x05cells\x18\a \x03(\v2\x13.replicationpb.CellR\x05cells\"/\n" +
	"\aVVEntry\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x10\n" +
	"\x03seq\x18\x02 \x01(\x04R\x03seq\";\n" +
	"\x11ExchangeVVRequest\x12&\n" +
	"\x02vv\x18\x01 \x03(\v2\x16.replicationpb.VVEntryR\x02vv\"<\n" +
	"\x12ExchangeVVResponse\x12&\n" +
	"\x02vv\x18\x01 \x03(\v2\x16.replicationpb.VVEntryR\x02vv\"T\n" +
	"\rGetOpsRequest\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x19\n" +
	"\bfrom_seq\x18\x02 \x01(\x04R\afromSeq\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"M\n" +
	"\x0eGetOpsResponse\x12#\n" +
	"\x03ops\x18\x01 \x03(\v2\x11.replicationpb.OpR\x03ops\x12\x16\n" +
	"\x06pruned\x18\x02 \x01(\bR\x06pruned\"X\n" +
	"\bAckEntry\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x10\n" +
	"\x03hlc\x18\x02 \x01(\x04R\x03hlc\x12&\n" +
	"\x02vv\x18\x03 \x03(\v2\x16.replicationpb.VVEntryR\x02vv\"B\n" +
	"\x13ExchangeAcksRequest\x12+\n" +
	"\x04acks\x18\x01 \x03(\v2\x17.replicationpb.AckEntryR\x04acks\"C\n" +
	"\x14ExchangeAcksResponse\x12+\n" +
	"\x04acks\x18\x01 \x03(\v2\x17.replicationpb.AckEntryR\x04acks\"w\n" +
	"\tClockCell\x12\x10\n" +
	"\x03tbl\x18\x01 \x01(\tR\x03tbl\x12\x0e\n" +
	"\x02pk\x18\x02 \x01(\fR\x02pk\x12\x10\n" +
	"\x03col\x18\x03 \x01(\tR\x03col\x12\x10\n" +
	"\x03hlc\x18\x04 \x01(\x04R\x03hlc\x12\x12\n" +
	"\x04site\x18\x05 \x01(\tR\x04site\x12\x10\n" +
	"\x03val\x18\x06 \x01(\fR\x03val\"0\n" +
	"\n" +
	"RangeEntry\x12\x12\n" +
	"\x04site\x18\x01 \x01(\tR\x04site\x12\x0e\n" +
	"\x02lo\x18\x02 \x01(\x04R\x02lo\"@\n" +
	"\x12GetSnapshotRequest\x12\x12\n" +
	"\x04part\x18\x01 \x01(\rR\x04part\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\fR\x06cursor\"\xe1\x01\n" +
	"\x13GetSnapshotResponse\x12#\n" +
	"\x03ops\x18\x01 \x03(\v2\x11.replicationpb.OpR\x03ops\x12.\n" +
	"\x06floors\x18\x02 \x03(\v2\x16.replicationpb.VVEntryR\x06floors\x121\n" +
	"\x06ranges\x18\x03 \x03(\v2\x19.replicationpb.RangeEntryR\x06ranges\x12.\n" +
	"\x05cells\x18\x04 \x03(\v2\x18.replicationpb.ClockCellR\x05cells\x12\x12\n" +
	"\x04next\x18\x05 \x01(\fR\x04next\"0\n" +
	"\vPushMessage\x12!\n" +
	"\x02op\x18\x01 \x01(\v2\x11.replicationpb.OpR\x02op\"\xa1\x02\n" +
	"\aRequest\x12C\n" +
	"\vexchange_vv\x18\x01 \x01(\v2 .replicationpb.ExchangeVVRequestH\x00R\n" +
	"exchangeVv\x127\n" +
	"\aget_ops\x18\x02 \x01(\v2\x1c.replicationpb.GetOpsRequestH\x00R\x06getOps\x12F\n" +
	"\fget_snapshot\x18\x03 \x01(\v2!.replicationpb.GetSnapshotRequestH\x00R\vgetSnapshot\x12I\n" +
	"\rexchange_acks\x18\x04 \x01(\v2\".replicationpb.ExchangeAcksRequestH\x00R\fexchangeAcksB\x05\n" +
	"\x03msg\"\xa6\x02\n" +
	"\bResponse\x12D\n" +
	"\vexchange_vv\x18\x01 \x01(\v2!.replicationpb.ExchangeVVResponseH\x00R\n" +
	"exchangeVv\x128\n" +
	"\aget_ops\x18\x02 \x01(\v2\x1d.replicationpb.GetOpsResponseH\x00R\x06getOps\x12G\n" +
	"\fget_snapshot\x18\x03 \x01(\v2\".replicationpb.GetSnapshotResponseH\x00R\vgetSnapshot\x12J\n" +
	"\rexchange_acks\x18\x04 \x01(\v2#.replicationpb.ExchangeAcksResponseH\x00R\fexchangeAcksB\x05\n" +
	"\x03msgB2Z0github.com/samyfodil/musql/examples/libp2p/pb;pbb\x06proto3"

var (
	file_transport_proto_rawDescOnce sync.Once
	file_transport_proto_rawDescData []byte
)

func file_transport_proto_rawDescGZIP() []byte {
	file_transport_proto_rawDescOnce.Do(func() {
		file_transport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)))
	})
	return file_transport_proto_rawDescData
}

var file_transport_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_transport_proto_goTypes = []any{
	(*Cell)(nil),                 // 0: replicationpb.Cell
	(*Op)(nil),                   // 1: replicationpb.Op
	(*VVEntry)(nil),              // 2: replicationpb.VVEntry
	(*ExchangeVVRequest)(nil),    // 3: replicationpb.ExchangeVVRequest
	(*ExchangeVVResponse)(nil),   // 4: replicationpb.ExchangeVVResponse
	(*GetOpsRequest)(nil),        // 5: replicationpb.GetOpsRequest
	(*GetOpsResponse)(nil),       // 6: replicationpb.GetOpsResponse
	(*AckEntry)(nil),             // 7: replicationpb.AckEntry
	(*ExchangeAcksRequest)(nil),  // 8: replicationpb.ExchangeAcksRequest
	(*ExchangeAcksResponse)(nil), // 9: replicationpb.ExchangeAcksResponse
	(*ClockCell)(nil),            // 10: replicationpb.ClockCell
	(*RangeEntry)(nil),           // 11: replicationpb.RangeEntry
	(*GetSnapshotRequest)(nil),   // 12: replicationpb.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),  // 13: replicationpb.GetSnapshotResponse
	(*PushMessage)(nil),          // 14: replicationpb.PushMessage
	(*Request)(nil),              // 15: replicationpb.Request
	(*Response)(nil),             // 16: replicationpb.Response
}
var file_transport_proto_depIdxs = []int32{
	0,  // 0: replicationpb.Op.cells:type_name -> replicationpb.Cell
	2,  // 1: replicationpb.ExchangeVVRequest.vv:type_name -> replicationpb.VVEntry
	2,  // 2: replicationpb.ExchangeVVResponse.vv:type_name -> replicationpb.VVEntry
	1,  // 3: replicationpb.GetOpsResponse.ops:type_name -> replicationpb.Op
	2,  // 4: replicationpb.AckEntry.vv:type_name -> replicationpb.VVEntry
	7,  // 5: replicationpb.ExchangeAcksRequest.acks:type_name -> replicationpb.AckEntry
	7,  // 6: replicationpb.ExchangeAcksResponse.acks:type_name -> replicationpb.AckEntry
	1,  // 7: replicationpb.GetSnapshotResponse.ops:type_name -> replicationpb.Op
	2,  // 8: replicationpb.GetSnapshotResponse.floors:type_name -> replicationpb.VVEntry
	11, // 9: replicationpb.GetSnapshotResponse.ranges:type_name -> replicationpb.RangeEntry
	10, // 10: replicationpb.GetSnapshotResponse.cells:type_name -> replicationpb.ClockCell
	1,  // 11: replicationpb.PushMessage.op:type_name -> replicationpb.Op
	3,  // 12: replicationpb.Request.exchange_vv:type_name -> replicationpb.ExchangeVVRequest
	5,  // 13: replicationpb.Request.get_ops:type_name -> replicationpb.GetOpsRequest
	12, // 14: replicationpb.Request.get_snapshot:type_name -> replicationpb.GetSnapshotRequest
	8,  // 15: replicationpb.Request.exchange_acks:type_name -> replicationpb.ExchangeAcksRequest
	4,  // 16: replicationpb.Response.exchange_vv:type_name -> replicationpb.ExchangeVVResponse
	6,  // 17: replicationpb.Response.get_ops:type_name -> replicationpb.GetOpsResponse
	13, // 18: replicationpb.Response.get_snapshot:type_name -> replicationpb.GetSnapshotResponse
	9,  // 19: replicationpb.Response.exchange_acks:type_name -> replicationpb.ExchangeAcksResponse
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_transport_proto_init() }
func file_transport_proto_init() {
	if File_transport_proto != nil {
		return
	}
	file_transport_proto_msgTypes[15].OneofWrappers = []any{
		(*Request_ExchangeVv)(nil),
		(*Request_GetOps)(nil),
		(*Request_GetSnapshot)(nil),
		(*Request_ExchangeAcks)(nil),
	}
	file_transport_proto_msgTypes[16].OneofWrappers = []any{
		(*Response_ExchangeVv)(nil),
		(*Response_GetOps)(nil),
		(*Response_GetSnapshot)(nil),
		(*Response_ExchangeAcks)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transport_proto_rawDesc), len(file_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transport_proto_goTypes,
		DependencyIndexes: file_transport_proto_depIdxs,
		MessageInfos:      file_transport_proto_msgTypes,
	}.Build()
	File_transport_proto = out.File
	file_transport_proto_goTypes = nil
	file_transport_proto_depIdxs = nil
}
